### ISSUE TITLE
Broken on latest posthtml (0.16+)

### ISSUE THREAD

**Issue by devinus** [posthtml/posthtml-render#58] opened 2021-06-04 08:10 UTC
Verified in several projects using htmlnano as a posthtml plugin.

**Comment by Scrum** [comment] 2021-06-08 09:10
@devinus @SukkaW @maltsev fixed in posthtml version v0.16.2

**Comment by maltsev** [comment] 2021-06-08 10:38
@Scrum thanks for a quick fix!

Still, in some cases, the returned HTML isn't the one we expect: https://travis-ci.org/github/posthtml/htmlnano/jobs/773915013

I guess it's related to recent changes in `posthtml-render` as well.

**Comment by Scrum** [comment] 2021-06-08 11:09
> @Scrum thanks for a quick fix!
> 
> Still, in some cases, the returned HTML isn't the one we expect: https://travis-ci.org/github/posthtml/htmlnano/jobs/773915013
> 
> I guess it's related to recent changes in `posthtml-render` as well.

Thanks, I'll see what the problem is

**Closed** 2021-06-10 14:09 UTC

**Comment by Scrum** [comment] 2021-06-10 14:19
@maltsev One of the tests in t[ravis](https://travis-ci.org/github/posthtml/htmlnano/jobs/774142770) is clearly failing due to rendering. 

I created a test for it and it passes successfully. 
https://github.com/posthtml/posthtml-render/blob/94603e598b4808c5abe50679b3ab02b8d930a2bc/test/test-core.spec.ts#L545-L557

Could you look at the possible reasons from the plugin side?

**Comment by maltsev** [comment] 2021-06-10 17:57
> Could you look at the possible reasons from the plugin side?

It seems that PostHTML renders numbers with single quotes:

```js
const posthtml = require('posthtml');
const html = '<img src="image.png" height="40" width="20">';

posthtml()
    .process(html)
    .then((result) => {
        console.log(result.html);
        // <img src="image.png" height='40' width='20'>
    });
```

[RunKit example](https://runkit.com/maltsev/60c251a126db30001a208854)

**Comment by Scrum** [comment] 2021-06-11 06:59
> It seems that PostHTML renders numbers with single quotes:

Thank you, I understand what the reason is. Fixed in https://github.com/posthtml/posthtml-render/pull/61
